[LinearSolve]
LoadMKL_JLL = false
autotune_timestamp = "2025-10-01T10:53:27.940"
best_algorithm_Float64_big = "OpenBLASLUFactorization"
best_algorithm_Float64_large = "AppleAccelerateLUFactorization"
best_algorithm_Float64_medium = "RFLUFactorization"
best_algorithm_Float64_small = "RFLUFactorization"
best_algorithm_Float64_tiny = "RFLUFactorization"
best_always_loaded_Float64_big = "AppleAccelerateLUFactorization"
best_always_loaded_Float64_large = "AppleAccelerateLUFactorization"
best_always_loaded_Float64_medium = "AppleAccelerateLUFactorization"
best_always_loaded_Float64_small = "LUFactorization"
best_always_loaded_Float64_tiny = "GenericLUFactorization"
